export const countries = [
  { label: 'Afghanistan', value: 'AF', dialcode: '+93' },
  { label: 'Albania', value: 'AL', dialcode: '+355' },
  { label: 'Algeria', value: 'DZ', dialcode: '+213' },
  { label: 'American Samoa', value: 'AS', dialcode: '+1-684' },
  { label: 'AndorrA', value: 'AD', dialcode: '+376' },
  { label: 'Angola', value: 'AO', dialcode: '+244' },
  { label: 'Anguilla', value: 'AI', dialcode: '+1-264' },
  { label: 'Antigua and Barbuda', value: 'AG', dialcode: '+1-268' },
  { label: 'Argentina', value: 'AR', dialcode: '+54' },
  { label: 'Armenia', value: 'AM', dialcode: '+374' },
  { label: 'Aruba', value: 'AW', dialcode: '+297' },
  { label: 'Australia', value: 'AU', dialcode: '+61' },
  { label: 'Austria', value: 'AT', dialcode: '+43' },
  { label: 'Azerbaijan', value: 'AZ', dialcode: '+994' },
  { label: 'Bahamas', value: 'BS', dialcode: '+1-242' },
  { label: 'Bahrain', value: 'BH', dialcode: '+973' },
  { label: 'Bangladesh', value: 'BD', dialcode: '+880' },
  { label: 'Barbados', value: 'BB', dialcode: '+1-246' },
  { label: 'Belarus', value: 'BY', dialcode: '+375' },
  { label: 'Belgium', value: 'BE', dialcode: '+32' },
  { label: 'Belize', value: 'BZ', dialcode: '+501' },
  { label: 'Benin', value: 'BJ', dialcode: '+229' },
  { label: 'Bermuda', value: 'BM', dialcode: '+1-441' },
  { label: 'Bhutan', value: 'BT', dialcode: '+975' },
  { label: 'Bolivia', value: 'BO', dialcode: '+591' },
  { label: 'Bosnia and Herzegovina', value: 'BA', dialcode: '+387' },
  { label: 'Botswana', value: 'BW', dialcode: '+267' },
  { label: 'Brazil', value: 'BR', dialcode: '+55' },
  { label: 'British Indian Ocean Territory', value: 'IO', dialcode: '+246' },
  { label: 'Bulgaria', value: 'BG', dialcode: '+359' },
  { label: 'Burkina Faso', value: 'BF', dialcode: '+226' },
  { label: 'Burundi', value: 'BI', dialcode: '+257' },
  { label: 'Cambodia', value: 'KH', dialcode: '+855' },
  { label: 'Cameroon', value: 'CM', dialcode: '+237' },
  { label: 'Canada', value: 'CA', dialcode: '+1' },
  { label: 'Cape Verde', value: 'CV', dialcode: '+238' },
  { label: 'Cayman Islands', value: 'KY', dialcode: '+1-345' },
  { label: 'Central African Republic', value: 'CF', dialcode: '+236' },
  { label: 'Chad', value: 'TD', dialcode: '+235' },
  { label: 'Chile', value: 'CL', dialcode: '+56' },
  { label: 'China', value: 'CN', dialcode: '+86' },
  { label: 'Christmas Island', value: 'CX', dialcode: '+61' },
  { label: 'Colombia', value: 'CO', dialcode: '+57' },
  { label: 'Comoros', value: 'KM', dialcode: '+269' },
  { label: 'Cook Islands', value: 'CK', dialcode: '+682' },
  { label: 'Costa Rica', value: 'CR', dialcode: '+506' },
  { label: 'Croatia', value: 'HR', dialcode: '+385' },
  { label: 'Cuba', value: 'CU', dialcode: '+53' },
  { label: 'Cyprus', value: 'CY', dialcode: '+357' },
  { label: 'Czech Republic', value: 'CZ', dialcode: '+420' },
  { label: 'Denmark', value: 'DK', dialcode: '+45' },
  { label: 'Djibouti', value: 'DJ', dialcode: '+253' },
  { label: 'Dominica', value: 'DM', dialcode: '+1-767' },
  { label: 'Dominican Republic', value: 'DO', dialcode: '+1-809' },
  { label: 'East Timor', value: 'TL', dialcode: '+670' },
  { label: 'Ecuador', value: 'EC', dialcode: '+593' },
  { label: 'Egypt', value: 'EG', dialcode: '+20' },
  { label: 'El Salvador', value: 'SV', dialcode: '+503' },
  { label: 'Equatorial Guinea', value: 'GQ', dialcode: '+240' },
  { label: 'Eritrea', value: 'ER', dialcode: '+291' },
  { label: 'Estonia', value: 'EE', dialcode: '+372' },
  { label: 'Ethiopia', value: 'ET', dialcode: '+251' },
  { label: 'Falkland Islands', value: 'FK', dialcode: '+500' },
  { label: 'Faroe Islands', value: 'FO', dialcode: '+298' },
  { label: 'Fiji', value: 'FJ', dialcode: '+679' },
  { label: 'Finland', value: 'FI', dialcode: '+358' },
  { label: 'France', value: 'FR', dialcode: '+33' },
  { label: 'French Polynesia', value: 'PF', dialcode: '+689' },
  { label: 'Gabon', value: 'GA', dialcode: '+241' },
  { label: 'Gambia', value: 'GM', dialcode: '+220' },
  { label: 'Georgia', value: 'GE', dialcode: '+995' },
  { label: 'Germany', value: 'DE', dialcode: '+49' },
  { label: 'Ghana', value: 'GH', dialcode: '+233' },
  { label: 'Gibraltar', value: 'GI', dialcode: '+350' },
  { label: 'Greece', value: 'GR', dialcode: '+30' },
  { label: 'Greenland', value: 'GL', dialcode: '+299' },
  { label: 'Grenada', value: 'GD', dialcode: '+1-473' },
  { label: 'Guam', value: 'GU', dialcode: '+1-671' },
  { label: 'Guatemala', value: 'GT', dialcode: '+502' },
  { label: 'Guernsey', value: 'GG', dialcode: '+44-1481' },
  { label: 'Guinea', value: 'GN', dialcode: '+224' },
  { label: 'Guinea-Bissau', value: 'GW', dialcode: '+245' },
  { label: 'Guyana', value: 'GY', dialcode: '+592' },
  { label: 'Haiti', value: 'HT', dialcode: '+509' },
  { label: 'Honduras', value: 'HN', dialcode: '+504' },
  { label: 'Hong Kong', value: 'HK', dialcode: '+852' },
  { label: 'Hungary', value: 'HU', dialcode: '+36' },
  { label: 'Iceland', value: 'IS', dialcode: '+354' },
  { label: 'India', value: 'IN', dialcode: '+91' },
  { label: 'Indonesia', value: 'ID', dialcode: '+62' },
  { label: 'Iran', value: 'IR', dialcode: '+98' },
  { label: 'Iraq', value: 'IQ', dialcode: '+964' },
  { label: 'Ireland', value: 'IE', dialcode: '+353' },
  { label: 'Isle of Man', value: 'IM', dialcode: '+44-1624' },
  { label: 'Italy', value: 'IT', dialcode: '+39' },
  { label: 'Ivory Coast', value: 'CI', dialcode: '+225' },
  { label: 'Jamaica', value: 'JM', dialcode: '+1-876' },
  { label: 'Japan', value: 'JP', dialcode: '+81' },
  { label: 'Jersey', value: 'JE', dialcode: '+44-1534' },
  { label: 'Jordan', value: 'JO', dialcode: '+962' },
  { label: 'Kazakhstan', value: 'KZ', dialcode: '+7' },
  { label: 'Kenya', value: 'KE', dialcode: '+254' },
  { label: 'Kiribati', value: 'KI', dialcode: '+686' },
  { label: 'Kosovo', value: 'XK', dialcode: '+383' },
  { label: 'Kuwait', value: 'KW', dialcode: '+965' },
  { label: 'Kyrgyzstan', value: 'KG', dialcode: '+996' },
  { label: 'Laos', value: 'LA', dialcode: '+856' },
  { label: 'Latvia', value: 'LV', dialcode: '+371' },
  { label: 'Lebanon', value: 'LB', dialcode: '+961' },
  { label: 'Lesotho', value: 'LS', dialcode: '+266' },
  { label: 'Liberia', value: 'LR', dialcode: '+231' },
  { label: 'Libya', value: 'LY', dialcode: '+218' },
  { label: 'Liechtenstein', value: 'LI', dialcode: '+423' },
  { label: 'Lithuania', value: 'LT', dialcode: '+370' },
  { label: 'Luxembourg', value: 'LU', dialcode: '+352' },
  { label: 'Macao', value: 'MO', dialcode: '+853' },
  { label: 'Republic of Macedonia', value: 'MK', dialcode: '+389' },
  { label: 'Madagascar', value: 'MG', dialcode: '+261' },
  { label: 'Malawi', value: 'MW', dialcode: '+265' },
  { label: 'Malaysia', value: 'MY', dialcode: '+60' },
  { label: 'Maldives', value: 'MV', dialcode: '+960' },
  { label: 'Mali', value: 'ML', dialcode: '+223' },
  { label: 'Malta', value: 'MT', dialcode: '+356' },
  { label: 'Mauritania', value: 'MR', dialcode: '+222' },
  { label: 'Mauritius', value: 'MU', dialcode: '+230' },
  { label: 'Mayotte', value: 'YT', dialcode: '+262' },
  { label: 'Mexico', value: 'MX', dialcode: '+52' },
  { label: 'Micronesia', value: 'FM', dialcode: '+691' },
  { label: 'Moldova', value: 'MD', dialcode: '+373' },
  { label: 'Monaco', value: 'MC', dialcode: '+377' },
  { label: 'Mongolia', value: 'MN', dialcode: '+976' },
  { label: 'Montenegro', value: 'ME', dialcode: '+382' },
  { label: 'Montserrat', value: 'MS', dialcode: '+1-664' },
  { label: 'Morocco', value: 'MA', dialcode: '+212' },
  { label: 'Mozambique', value: 'MZ', dialcode: '+258' },
  { label: 'Myanmar', value: 'MM', dialcode: '+95' },
  { label: 'Namibia', value: 'NA', dialcode: '+264' },
  { label: 'Nauru', value: 'NR', dialcode: '+674' },
  { label: 'Nepal', value: 'NP', dialcode: '+977' },
  { label: 'Netherlands', value: 'NL', dialcode: '+31' },
  { label: 'New Caledonia', value: 'NC', dialcode: '+687' },
  { label: 'New Zealand', value: 'NZ', dialcode: '+64' },
  { label: 'Nicaragua', value: 'NI', dialcode: '+505' },
  { label: 'Niger', value: 'NE', dialcode: '+227' },
  { label: 'Nigeria', value: 'NG', dialcode: '+234' },
  { label: 'Niue', value: 'NU', dialcode: '+683' },
  { label: 'North Korea', value: 'KP', dialcode: '+850' },
  { label: 'Northern Mariana Islands', value: 'MP', dialcode: '+1-670' },
  { label: 'Norway', value: 'NO', dialcode: '+47' },
  { label: 'Oman', value: 'OM', dialcode: '+968' },
  { label: 'Pakistan', value: 'PK', dialcode: '+92' },
  { label: 'Palau', value: 'PW', dialcode: '+680' },
  { label: 'Palestine', value: 'PS', dialcode: '+970' },
  { label: 'Panama', value: 'PA', dialcode: '+507' },
  { label: 'Papua New Guinea', value: 'PG', dialcode: '+675' },
  { label: 'Paraguay', value: 'PY', dialcode: '+696' },
  { label: 'Peru', value: 'PE', dialcode: '+51' },
  { label: 'Philippines', value: 'PH', dialcode: '+63' },
  { label: 'Pitcairn', value: 'PN', dialcode: '+64' },
  { label: 'Poland', value: 'PL', dialcode: '+48' },
  { label: 'Portugal', value: 'PT', dialcode: '+351' },
  { label: 'Puerto Rico', value: 'PR', dialcode: '+1-787' },
  { label: 'Qatar', value: 'QA', dialcode: '+974' },
  { label: 'Romania', value: 'RO', dialcode: '+40' },
  { label: 'Russia', value: 'RU', dialcode: '+7' },
  { label: 'RWANDA', value: 'RW', dialcode: '+250' },
  { label: 'Samoa', value: 'WS', dialcode: '+685' },
  { label: 'San Marino', value: 'SM', dialcode: '+378' },
  { label: 'Sao Tome and Principe', value: 'ST', dialcode: '+239' },
  { label: 'Saudi Arabia', value: 'SA', dialcode: '+966' },
  { label: 'Senegal', value: 'SN', dialcode: '+221' },
  { label: 'Serbia', value: 'RS', dialcode: '+381' },
  { label: 'Seychelles', value: 'SC', dialcode: '+248' },
  { label: 'Sierra Leone', value: 'SL', dialcode: '+232' },
  { label: 'Singapore', value: 'SG', dialcode: '+65' },
  { label: 'Sint Maarten', value: 'SX', dialcode: '+1-721' },
  { label: 'Slovakia', value: 'SK', dialcode: '+421' },
  { label: 'Slovenia', value: 'SI', dialcode: '+386' },
  { label: 'Solomon Islands', value: 'SB', dialcode: '+677' },
  { label: 'Somalia', value: 'SO', dialcode: '+252' },
  { label: 'South Africa', value: 'ZA', dialcode: '+27' },
  { label: 'South Korea', value: 'KR', dialcode: '+82' },
  { label: 'South Africa', value: 'ZA', dialcode: '+27' },
  { label: 'Spain', value: 'ES', dialcode: '+34' },
  { label: 'Sri Lanka', value: 'LK', dialcode: '+94' },
  { label: 'Sudan', value: 'SD', dialcode: '+249' },
  { label: 'Surilabel', value: 'SR', dialcode: '+597' },
  { label: 'Svalbard and Jan Mayen', value: 'SJ', dialcode: '+47' },
  { label: 'Sweden', value: 'SE', dialcode: '+46' },
  { label: 'Switzerland', value: 'CH', dialcode: '+41' },
  { label: 'Syria', value: 'SY', dialcode: '+963' },
  { label: 'Taiwan', value: 'TW', dialcode: '+886' },
  { label: 'Tajikistan', value: 'TJ', dialcode: '+992' },
  { label: 'Tanzania', value: 'TZ', dialcode: '+255' },
  { label: 'Thailand', value: 'TH', dialcode: '+66' },
  { label: 'Togo', value: 'TG', dialcode: '+228' },
  { label: 'Tokelau', value: 'TK', dialcode: '+690' },
  { label: 'Tonga', value: 'TO', dialcode: '+676' },
  { label: 'Trinidad and Tobago', value: 'TT', dialcode: '+1-868' },
  { label: 'Tunisia', value: 'TN', dialcode: '+216' },
  { label: 'Turkey', value: 'TR', dialcode: '+90' },
  { label: 'Turkmenistan', value: 'TM', dialcode: '+993' },
  { label: 'Uganda', value: 'UG', dialcode: '+256' },
  { label: 'Ukraine', value: 'UA', dialcode: '+380' },
  { label: 'United Arab Emirates', value: 'AE', dialcode: '+971' },
  { label: 'United Kingdom', value: 'GB', dialcode: '+44' },
  { label: 'United States of America', value: 'US', dialcode: '+1' },
  { label: 'Uruguay', value: 'UY', dialcode: '+598' },
  { label: 'Uzbekistan', value: 'UZ', dialcode: '+998' },
  { label: 'Vanuatu', value: 'VU', dialcode: '+678' },
  { label: 'Vatican', value: 'VA', dialcode: '+379' },
  { label: 'Venezuela', value: 'VE', dialcode: '+58' },
  { label: 'vietnam', value: 'VN', dialcode: '+84' },
  { label: 'Western Sahara', value: 'EH', dialcode: '+212' },
  { label: 'Yemen', value: 'YE', dialcode: '+967' },
  { label: 'Zambia', value: 'ZM', dialcode: '+260' },
  { label: 'Zimbabwe', value: 'ZW', dialcode: '+263' },
]
